select 
min(AMOUNT), /* EN DÜÞÜK SATIÞ ADEDÝ*/
max(AMOUNT), /* EN YÜKSEK SATIÞ ADEDÝ*/
AVG(AMOUNT),/* SATIÞ ADEDÝ ORTALAMASI*/
COUNT(AMOUNT),/*SATIÞ ADEDÝ SAYISI*/
SUM(AMOUNT)/*SATIÞ ADEDÝ TOPLAMI*/
From SALES

SELECT CITY , 
SUM(TOTALPRICE) AS TOTALPRÝCE

FROM SALES

GROUP BY CITY

ORDER BY SUM(TOTALPRICE) DESC /* SALES TABLOSUNDAN EN YÜKSEK SATIÞ TOPLAMINA SAHÝP ÝLLERÝ SIRALA*/



